### ISSUE TITLE
Password string too short error

### ISSUE THREAD

**Issue by taetaetae** [hmalphettes/kibana-auth-plugin#10]
You have received the following error while running the plug-in :
```
$ LOCAL_AUTH_LOGINS=admin:password,foo:bar bin/kibana
  log   [16:46:59.462] [info][status][plugin:kibana@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.505] [info][status][plugin:elasticsearch@1.0.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [16:46:59.812] [info][status][plugin:kibana-auth-plugin@0.1.1] Status changed from uninitialized to green - Ready
  log   [16:46:59.819] [info][status][plugin:kbn_vislib_vis_types@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.835] [info][status][plugin:markdown_vis@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.839] [info][status][plugin:elasticsearch@1.0.0] Status changed from yellow to green - Kibana index ready
  log   [16:46:59.845] [info][status][plugin:metric_vis@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.850] [info][status][plugin:spyModes@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.853] [info][status][plugin:statusPage@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.857] [info][status][plugin:table_vis@1.0.0] Status changed from uninitialized to green - Ready
  log   [16:46:59.863] [info][listening] Server running at http://~~~:5601
 error  [16:47:22.175]  Error: Failed to encode cookie (sid) value: Password string too short (min 32 characters required)
    at internals.encode (/~~~/kibana-4.6.4-linux-x86_64/node_modules/statehood/lib/index.js:450:34)
    at process.nextTick (/~~~/kibana-4.6.4-linux-x86_64/node_modules/statehood/node_modules/hoek/lib/index.js:854:22)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Debug: internal, implementation, error
    Error: Failed to encode cookie (sid) value: Password string too short (min 32 characters required)
    at internals.encode (/~~~/kibana-4.6.4-linux-x86_64/node_modules/statehood/lib/index.js:450:34)
    at process.nextTick (/~~~/kibana-4.6.4-linux-x86_64/node_modules/statehood/node_modules/hoek/lib/index.js:854:22)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

We ask you to help us find out where you did wrong.

**Comment by lmangani** [comment]
Something changed in ```hoek``` library evidently, this is not your mistake, it would affect any user. Please standby for updates.

**Comment by lmangani** [comment]
Please re-test with 0.1.2: https://github.com/elasticfence/kibana-auth-plugin/releases/tag/0.1.2

**Comment by taetaetae** [comment]
As we execute it, the following errors occur. T.T
```
install
$ bin/kibana plugin --install kibana-auth-plugin -u https://github.com/elasticfence/kibana-auth-plugin/releases/download/0.1.2/kauth-latest.tar.gz

execute
$ LOCAL_AUTH_LOGINS=admin:password,foo:bar bin/kibana
  log   [17:14:21.852] [info][status][plugin:kibana@1.0.0] Status changed from uninitialized to green - Ready
  log   [17:14:21.895] [info][status][plugin:elasticsearch@1.0.0] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [17:14:22.380] [fatal] ReferenceError: salt is not defined
    at /~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/server/auth-local-cookie.js:79:28
    at Items.serial (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/lib/plugin.js:323:16)
    at done (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Object.exports.register (/~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/node_modules/hapi-auth-cookie/lib/index.js:15:5)
    at Object.target [as register] (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at internals.Plugin.register (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/lib/plugin.js:320:11)
    at module.exports (/~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/server/auth-local-cookie.js:69:10)
    at ScopedPlugin.init [as externalInit] (/~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/index.js:17:44)
    at ScopedPlugin.tryCatcher (/~~~/kibana-4.6.4-linux-x86_64/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/~~~/kibana-4.6.4-linux-x86_64/node_modules/bluebird/js/main/method.js:30:24)
    at ScopedPlugin.asyncRegister$ (/~~~/kibana-4.6.4-linux-x86_64/src/server/plugins/Plugin.js:142:63)
    at tryCatch (/~~~/kibana-4.6.4-linux-x86_64/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/~~~/kibana-4.6.4-linux-x86_64/node_modules/babel-runtime/regenerator/runtime.js:315:22)
FATAL ReferenceError: salt is not defined
    at /~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/server/auth-local-cookie.js:79:28
    at Items.serial (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/lib/plugin.js:323:16)
    at done (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Object.exports.register (/~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/node_modules/hapi-auth-cookie/lib/index.js:15:5)
    at Object.target [as register] (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/joi/lib/object.js:77:34)
    at each (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/lib/plugin.js:317:14)
    at iterate (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/node_modules/items/lib/index.js:39:9)
    at internals.Plugin.register (/~~~/kibana-4.6.4-linux-x86_64/node_modules/hapi/lib/plugin.js:320:11)
    at module.exports (/~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/server/auth-local-cookie.js:69:10)
    at ScopedPlugin.init [as externalInit] (/~~~/kibana-4.6.4-linux-x86_64/installedPlugins/kibana-auth-plugin/index.js:17:44)
    at ScopedPlugin.tryCatcher (/~~~/kibana-4.6.4-linux-x86_64/node_modules/bluebird/js/main/util.js:26:23)
    at Function.Promise.attempt.Promise.try (/~~~/kibana-4.6.4-linux-x86_64/node_modules/bluebird/js/main/method.js:30:24)
    at ScopedPlugin.asyncRegister$ (/~~~/kibana-4.6.4-linux-x86_64/src/server/plugins/Plugin.js:142:63)
    at tryCatch (/~~~/kibana-4.6.4-linux-x86_64/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/~~~/kibana-4.6.4-linux-x86_64/node_modules/babel-runtime/regenerator/runtime.js:315:22)
```

**Comment by lmangani** [comment]
my bad - release updated, kindly re-test

**Comment by taetaetae** [comment]
Wow!That's fine.
Thank you very much for your prompt response !!
Full of luck.

**Comment by lmangani** [comment]
Thanks & Enjoy!
