### ISSUE TITLE
Error intsalling plugin Kibana 5.6.2

### ISSUE THREAD

**Issue by ameygat** [hmalphettes/kibana-auth-plugin#13]
I have tried installing plugin in kibana 5.6.2 but get following error:

`
ubuntu@minemeld1:~/proxy/kibana-5.6.2-linux-x86_64$ bin/kibana-plugin install https://github.com/elasticfence/kibana-auth-plugin/releases/download/0.1.1/kauth-latest.tar.gz
Attempting to transfer from https://github.com/elasticfence/kibana-auth-plugin/releases/download/0.1.1/kauth-latest.tar.gz
Transferring 849844 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /home/ubuntu/proxy/kibana-5.6.2-linux-x86_64/node_modules/yauzl/index.js:179:14
    at /home/ubuntu/proxy/kibana-5.6.2-linux-x86_64/node_modules/yauzl/index.js:539:5
    at /home/ubuntu/proxy/kibana-5.6.2-linux-x86_64/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"
`

**Comment by gunjan-kumar-mehta** [comment]
Getting the same error. have you found any solution or workaround?
